[platformio]
src_dir = .
default_envs = d1_mini

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
lib_deps =
    PubSubClient
    Adafruit NeoPixel
    Adafruit NeoMatrix
    Adafruit GFX Library
